name: CityLounge
favicon: null
layout_spectrum: 0.06987
typography_spectrum: 0.32489
title: CityLounge
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#2e70ac'
    - '#91bdd8'
    - '#a59272'
    - '#e7e9e8'
  brandStrength: 0.14757646154612303
  lightness: 0.0625
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
