title: CityLounge
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2795699
  brandStrength: 0.5
  lightness: 0.7580645
  brandColors:
    - '#020202'
    - '#2e70ac'
    - '#91bdd8'
    - '#a59272'
    - '#e7e9e8'
  rhythmicContrast: 0.8136201
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: CityLounge
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.30158
layout_spectrum: 0.86864
