typography_spectrum: 0.22338
color:
  saturation: 0.4731183
  brandStrength: 1
  lightness: 0.4086021
  brandColors:
    - '#030503'
    - '#3979B6'
    - '#97C0D9'
    - '#807259'
    - '#54585B'
  rhythmicContrast: 0.4139785
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9333895
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: Alexander Czernay
name: CityLounge
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: CityLounge
content: []
purpose: []
