title: CityLounge
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4731183
  brandStrength: 1
  lightness: 0.4086021
  brandColors:
    - '#030503'
    - '#3979B6'
    - '#97C0D9'
    - '#807259'
    - '#54585B'
  rhythmicContrast: 0.4139785
cta:
  bucket: null
  version: null
  domain: null
name: CityLounge
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.22338
layout_spectrum: 0.9333895
