name: CityLounge
favicon: null
layout_spectrum: 0.86864
typography_spectrum: 0.30158
title: CityLounge
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#2e70ac'
    - '#91bdd8'
    - '#a59272'
    - '#e7e9e8'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
